# Generated by Django 4.2.16 on 2024-11-23 23:14

import django.core.validators
import django.db.models.deletion
import pricing.models.defaults.default_pricing_week
import pricing.models.defaults.default_pricing_year
import utilities.models.validators.greater_than_zero
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      ('items', '0002_alter_packaging_quantity'),
      ('stores', '0001_initial'),
  ]

  operations = [
      migrations.CreateModel(
          name='Price',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'amount',
                  models.DecimalField(
                      decimal_places=2,
                      max_digits=11,
                      validators=[
                          utilities.models.validators.greater_than_zero.
                          validator_greater_than_zero
                      ]
                  )
              ),
              (
                  'week',
                  models.IntegerField(
                      default=pricing.models.defaults.default_pricing_week.
                      default_pricing_week,
                      validators=[
                          django.core.validators.MinValueValidator(1),
                          django.core.validators.MaxValueValidator(53)
                      ]
                  )
              ),
              (
                  'year',
                  models.IntegerField(
                      default=pricing.models.defaults.default_pricing_year.
                      default_pricing_year,
                      validators=[
                          django.core.validators.MinValueValidator(2024),
                          django.core.validators.MaxValueValidator(2100)
                      ]
                  )
              ),
              (
                  'item',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      to='items.item'
                  )
              ),
              (
                  'store',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      to='stores.store'
                  )
              ),
          ],
          options={
              'verbose_name_plural': 'Pricing',
              'unique_together': {('item', 'store', 'week', 'year')},
          },
      ),
  ]
