# Generated by Django 4.2.16 on 2024-09-05 18:02

import address.models
import django.db.models.deletion
import django.db.models.functions.text
import utilities.models.fields.blonde
from django.db import migrations, models


class Migration(migrations.Migration):
  initial = True

  dependencies = [
      ("address", "0003_auto_20200830_1851"),
      ("scrapers", "0001_initial"),
  ]

  operations = [
      migrations.CreateModel(
          name="Franchise",
          fields=[
              (
                  "id",
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name="ID"
                  ),
              ),
              (
                  "name",
                  utilities.models.fields.blonde.BlondeCharField(max_length=80)
              ),
              (
                  "scraper",
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.PROTECT,
                      to="scrapers.scraper"
                  ),
              ),
          ],
      ),
      migrations.CreateModel(
          name="Store",
          fields=[
              (
                  "id",
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name="ID"
                  ),
              ),
              (
                  "franchise_location",
                  utilities.models.fields.blonde.BlondeCharField(max_length=80),
              ),
              (
                  "address",
                  address.models.AddressField(
                      on_delete=django.db.models.deletion.PROTECT,
                      to="address.address"
                  ),
              ),
              (
                  "franchise",
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.PROTECT,
                      to="stores.franchise"
                  ),
              ),
          ],
          options={
              "unique_together": {("franchise", "franchise_location")},
          },
      ),
      migrations.AddConstraint(
          model_name="franchise",
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower("name"),
              name="Franchise name must be unique",
          ),
      ),
  ]
