# Generated by Django 4.2.16 on 2024-09-05 18:02

import django.db.models.deletion
import django.db.models.functions.text
import utilities.models.fields.title
import utilities.models.validators.regex
from django.db import migrations, models
from utilities.models.validators.regex_with_n_capture_groups import (
    create_validator_regex_with_n_capture_groups,
)


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
      migrations.CreateModel(
          name="Scraper",
          fields=[
              (
                  "id",
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name="ID"
                  )
              ),
              ("name", utilities.models.fields.title.TitleField(max_length=80)),
              ("pricing_selector", models.CharField(max_length=250)),
              (
                  "pricing_regex",
                  models.CharField(
                      max_length=250,
                      validators=[
                          utilities.models.validators.regex.validator_regex
                      ]
                  )
              ),
              ("pricing_bulk_selector", models.CharField(max_length=250)),
              (
                  "pricing_bulk_regex",
                  models.CharField(
                      max_length=250,
                      validators=[
                          utilities.models.validators.regex.validator_regex
                      ]
                  )
              ),
              (
                  "url_validation_regex",
                  models.CharField(
                      max_length=250,
                      validators=[
                          create_validator_regex_with_n_capture_groups(2)
                      ]
                  )
              ),
          ],
      ),
      migrations.CreateModel(
          name="ScraperConfig",
          fields=[
              (
                  "id",
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name="ID"
                  )
              ),
              ("url", models.CharField(max_length=250)),
              (
                  "scraper",
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.PROTECT,
                      to="scrapers.scraper"
                  )
              ),
          ],
          options={
              "abstract": False,
          },
      ),
      migrations.AddConstraint(
          model_name="scraper",
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower("name"),
              name="Scraper name must be unique"
          ),
      ),
  ]
