# Generated by Django 4.2.28 on 2026-02-18 20:18

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
      ("scrapers", "0001_initial"),
  ]

  operations = [
      migrations.RemoveField(
          model_name="scraper",
          name="pricing_bulk_regex",
      ),
      migrations.RemoveField(
          model_name="scraper",
          name="pricing_bulk_selector",
      ),
      migrations.RemoveField(
          model_name="scraper",
          name="pricing_regex",
      ),
      migrations.RemoveField(
          model_name="scraper",
          name="pricing_selector",
      ),
  ]
