# Generated by Django 4.2.28 on 2026-02-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('scrapers', '0002_remove_scraper_pricing_bulk_regex_and_more'),
  ]

  operations = [
      migrations.AddField(
          model_name='scraperconfig',
          name='is_active',
          field=models.BooleanField(default=True),
      ),
  ]
