# Generated by Django 4.2.28 on 2026-02-26 10:48

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
      ("scrapers", "0003_scraperconfig_is_active"),
  ]

  operations = [
      migrations.AddConstraint(
          model_name="scraperconfig",
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower("url"),
              name="URL name must be unique"
          ),
      ),
  ]
