---
default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.3.3
    hooks:
      - id: python-safety-dependencies-check
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.32.0
    hooks:
      - id: yamllint
        args:
          - "-c"
          - "./.yamllint.yml"
        stages: [pre-commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        entry: "ruff check"
        args:
          - "--select"
          - "I"
          - "--fix"
        types: ["python"]
      - id: ruff-check
  - repo: https://github.com/cicd-tools-org/pre-commit.git
    rev: 0.6.0
    hooks:
      - id: format-shell
        args:
          - "-w"
          - "--indent=2"
          - "-ci"
          - "-sr"
      - id: format-toml
      - id: git-conflict-markers
      - id: lint-github-workflow
      - id: lint-github-workflow-header
      - id: lint-markdown
        args:
          - "-c"
          - ".markdownlint.yml"
      - id: lint-shell
        args:
          - "--color=always"
          - "--source-path=SCRIPTDIR"
          - "--exclude=SC2317"
          - "-x"
      - id: poetry-types-python
        entry: bash -c 'PYTHONPATH=./cross_shopper poetry run mypy cross_shopper/'
      - id: pre-commit-sort-config
      - id: security-credentials
      - id: spelling-commit-message
      - id: spelling-markdown
      - id: spelling-vale-sync
      - id: spelling-vale-vocab
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.2.2
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/google/yapf
    rev: v0.40.2
    hooks:
      - id: yapf
        name: "yapf"
        args:
          - "-i"
          - "--parallel"
        types: []
        files: "^.+\\.pyi?$"
        stages: [pre-commit]
        require_serial: true
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.22.0
    hooks:
      - id: check-jsonschema
        name: check-github-workflow-push-schema
        files: "^\\.github/config/workflows/workflow-push.json$"
        args:
          - "--schemafile"
          - ".github/config/schemas/workflows/workflow-push.json"
        stages: [pre-commit]
  - repo: local
    hooks:
      - id: django-model-id
        name: avoid referencing models by id
        entry: '\.id'
        language: pygrep
        files: "^cross_shopper/.+\\.py$"
        stages: [pre-commit]
      - id: django-serializer-docstrings
        name: ensure serializer modules have correct docstrings
        entry: '\A(?!"""Serializer to (retrieve, list, create or update|retrieve or list) (a |an |)[A-Z]{1}[A-Za-z]+."""\n.+class [A-Z]{1}[A-Za-z]+\(.+\):\n  """Serializer to (retrieve, list, create or update|retrieve or list) (a |an |)[A-Z]{1}[A-Za-z]+."""\n).+\Z'
        args: [--multiline]
        language: pygrep
        files: "^cross_shopper/[a-z_]+/models/serializers/(read_write|read_only)/(?!__init__.py$)(?!report_summary|report_pricing)(?!.*test.*)(?!.+internal).+\\.py$"
        stages: [pre-commit]
      - id: imports
        name: ensure multi-level relative imports are not used
        entry: '\A.*from \.[\.]+.*\Z'
        args: [--multiline]
        language: pygrep
        files: "^cross_shopper/(?!.*(migrations).*).+\\.py$"
        stages: [pre-commit]
      - id: test-docstrings
        name: ensure docstrings are not used in test functions
        entry: '\A.+(\s*def test_[a-z0-9_]+\(.+\) -> None:\n\s*""".+"""\n).+\Z'
        args: [--multiline]
        language: pygrep
        files: "^cross_shopper/(?=.*test_.*)(?!.*(migrations).*).+\\.py$"
        stages: [pre-commit]
      - id: test-docstrings
        name: ensure docstrings are correct in test modules
        entry: '\A("""[A-Z]{1}.+\."""\n).+\nclass [A-Za-z_]+(\(.+\)){0,1}:\n  """.+""".+\Z'
        args: [--multiline]
        language: pygrep
        files: "^cross_shopper/(?=.*test_.*)(?!.*(migrations).*).+\\.py$"
        stages: [pre-commit]
      - id: test-fixtures
        name: ensure test fixures are not inside test modules
        entry: "^@pytest.fixture$"
        language: pygrep
        files: "^cross_shopper/(?=.*test_.*).+\\.py$"
        stages: [pre-commit]
      - id: test-fixtures
        name: ensure test fixures for models are named correctly and don't cohabitate with mocks
        entry: '\A.+(@pytest.fixture\(\)|@pytest.fixture\ndef mock.+).+\Z'
        args: [--multiline]
        language: pygrep
        files: "^cross_shopper/(?=.*models/fixtures.*).+\\.py$"
        stages: [pre-commit]
      - id: test-fixtures
        name: ensure test fixures for mocks are named correctly and are kept in conftest.py files
        entry: '\A.+(@pytest.fixture\(\)|@pytest.fixture\ndef mock_.+).+\Z'
        args: [--multiline]
        language: pygrep
        files: "^cross_shopper/(?=.*conftest.py).+\\.py$"
        stages: [pre-commit]
