# Generated by Django 4.2.16 on 2024-09-05 18:02

import django.db.models.deletion
import django.db.models.functions.text
import utilities.models.fields.blonde
import utilities.models.fields.title
import utilities.models.validators.non_zero
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      ('scrapers', '0001_initial'),
  ]

  operations = [
      migrations.CreateModel(
          name='Brand',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'name',
                  utilities.models.fields.blonde.BlondeCharField(max_length=80)
              ),
          ],
      ),
      migrations.CreateModel(
          name='Item',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              ('is_non_gmo', models.BooleanField()),
              ('is_organic', models.BooleanField()),
              (
                  'name',
                  utilities.models.fields.blonde.BlondeCharField(max_length=80)
              ),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.CreateModel(
          name='ItemScraperConfig',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.CreateModel(
          name='Packaging',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'quantity',
                  models.DecimalField(
                      blank=True,
                      decimal_places=2,
                      max_digits=11,
                      null=True,
                      validators=[
                          utilities.models.validators.non_zero.
                          validator_non_zero
                      ]
                  )
              ),
          ],
          options={
              'verbose_name_plural': 'Packaging',
          },
      ),
      migrations.CreateModel(
          name='PackagingContainer',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              ('name', utilities.models.fields.title.TitleField(max_length=80)),
          ],
      ),
      migrations.CreateModel(
          name='PackagingUnit',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'name',
                  utilities.models.fields.blonde.BlondeCharField(max_length=80)
              ),
          ],
      ),
      migrations.AddConstraint(
          model_name='packagingunit',
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower('name'),
              name='PackagingUnit name must be unique'
          ),
      ),
      migrations.AddConstraint(
          model_name='packagingcontainer',
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower('name'),
              name='PackagingContainer name must be unique'
          ),
      ),
      migrations.AddField(
          model_name='packaging',
          name='container',
          field=models.ForeignKey(
              blank=True,
              null=True,
              on_delete=django.db.models.deletion.PROTECT,
              to='items.packagingcontainer'
          ),
      ),
      migrations.AddField(
          model_name='packaging',
          name='unit',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT,
              to='items.packagingunit'
          ),
      ),
      migrations.AddField(
          model_name='itemscraperconfig',
          name='item',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT, to='items.item'
          ),
      ),
      migrations.AddField(
          model_name='itemscraperconfig',
          name='scraper_config',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT,
              to='scrapers.scraperconfig'
          ),
      ),
      migrations.AddField(
          model_name='item',
          name='brand',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT, to='items.brand'
          ),
      ),
      migrations.AddField(
          model_name='item',
          name='packaging',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT, to='items.packaging'
          ),
      ),
      migrations.AddField(
          model_name='item',
          name='scraper_config',
          field=models.ManyToManyField(
              through='items.ItemScraperConfig', to='scrapers.scraperconfig'
          ),
      ),
      migrations.AddConstraint(
          model_name='brand',
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower('name'),
              name='Brand name must be unique'
          ),
      ),
      migrations.AlterUniqueTogether(
          name='packaging',
          unique_together={('quantity', 'container', 'unit')},
      ),
  ]
