# Generated by Django 4.2.16 on 2024-11-23 23:08

import utilities.models.validators.greater_than_zero
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ("items", "0001_initial"),
  ]

  operations = [
      migrations.AlterField(
          model_name="packaging",
          name="quantity",
          field=models.DecimalField(
              blank=True,
              decimal_places=2,
              max_digits=11,
              null=True,
              validators=[
                  utilities.models.validators.greater_than_zero.
                  validator_greater_than_zero
              ]
          ),
      ),
  ]
