# Generated by Django 4.2.28 on 2026-02-23 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ("scrapers", "0003_scraperconfig_is_active"),
      ("items", "0002_alter_packaging_quantity"),
  ]

  operations = [
      migrations.AlterUniqueTogether(
          name="itemscraperconfig",
          unique_together={("item", "scraper_config")},
      ),
      migrations.AddConstraint(
          model_name="itemscraperconfig",
          constraint=models.UniqueConstraint(
              fields=("scraper_config",), name="unique_scraper_config"
          ),
      ),
  ]
