# Generated by Django 4.2.28 on 2026-02-25 23:37

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

  dependencies = [
      ("items", "0003_alter_itemscraperconfig_constraints"),
  ]

  operations = [
      migrations.AlterModelManagers(
          name="itemscraperconfig",
          managers=[
              ("associations", django.db.models.manager.Manager()),
          ],
      ),
  ]
