# Generated by Django 4.2.29 on 2026-03-05 18:54

import django.db.models.deletion
import django.db.models.functions.text
import utilities.models.fields.blonde
from django.db import migrations, models
from utilities.models.validators.restricted_values import (
    create_restricted_values_validator,
)


class Migration(migrations.Migration):

  dependencies = [
      ('items', '0004_alter_itemscraperconfig_managers'),
  ]

  operations = [
      migrations.CreateModel(
          name='Attribute',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'name',
                  utilities.models.fields.blonde.BlondeCharField(
                      max_length=80,
                      validators=[
                          create_restricted_values_validator(frozenset({','})),
                      ]
                  )
              ),
          ],
      ),
      migrations.CreateModel(
          name='ItemAttribute',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'attribute',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      to='items.attribute'
                  )
              ),
              (
                  'item',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      to='items.item'
                  )
              ),
          ],
      ),
      migrations.AddConstraint(
          model_name='attribute',
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower('name'),
              name='Attribute name must be unique'
          ),
      ),
      migrations.AddField(
          model_name='item',
          name='attribute',
          field=models.ManyToManyField(
              through='items.ItemAttribute', to='items.attribute'
          ),
      ),
      migrations.AlterUniqueTogether(
          name='itemattribute',
          unique_together={('item', 'attribute')},
      ),
      migrations.AlterModelManagers(
          name='itemattribute',
          managers=[
              ('associations', django.db.models.manager.Manager()),
          ],
      ),
  ]
