# Generated by Django 4.2.29 on 2026-03-12 18:41

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import utilities.models.fields.blonde
import utilities.models.validators.greater_than_zero
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
      ("items", "0007_refactored_title_field"),
  ]

  operations = [
      migrations.CreateModel(
          name="PriceGroup",
          fields=[
              (
                  "id",
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name="ID"
                  ),
              ),
              ("is_non_gmo", models.BooleanField()),
              ("is_organic", models.BooleanField()),
              (
                  "name",
                  utilities.models.fields.blonde.BlondeCharField(max_length=80)
              ),
              (
                  "quantity",
                  models.PositiveIntegerField(
                      validators=[
                          utilities.models.validators.greater_than_zero.
                          validator_greater_than_zero,
                          django.core.validators.MaxValueValidator(1000),
                      ]
                  ),
              ),
              (
                  "unit",
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.PROTECT,
                      to="items.packagingunit"
                  ),
              ),
          ],
      ),
      migrations.AddField(
          model_name="item",
          name="price_group",
          field=models.ForeignKey(
              blank=True,
              null=True,
              on_delete=django.db.models.deletion.PROTECT,
              to="items.pricegroup",
          ),
      ),
      migrations.AlterUniqueTogether(
          name="pricegroup",
          unique_together={
              (
                  "name",
                  "is_non_gmo",
                  "is_organic",
                  "quantity",
                  "unit",
              )
          },
      ),
      migrations.CreateModel(
          name="PriceGroupAttribute",
          fields=[
              (
                  "id",
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name="ID"
                  ),
              ),
              (
                  "attribute",
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      to="items.attribute"
                  ),
              ),
              (
                  "price_group",
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.CASCADE,
                      to="items.pricegroup"
                  ),
              ),
          ],
          options={
              "unique_together": {("price_group", "attribute")},
          },
          managers=[
              ("associations", django.db.models.manager.Manager()),
          ],
      ),
      migrations.AddField(
          model_name="pricegroup",
          name="attribute",
          field=models.ManyToManyField(
              through="items.PriceGroupAttribute", to="items.attribute"
          ),
      ),
  ]
