# Generated by Django 4.2.29 on 2026-03-12 19:09

from re import I
from typing import TYPE_CHECKING, cast

import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models, transaction
from items import constants

if TYPE_CHECKING:
  from django.apps.registry import Apps
  from django.db.backends.base.schema import BaseDatabaseSchemaEditor
  from items.models import Item, PriceGroup


def forwards_func(
    apps: "Apps",
    schema_editor: "BaseDatabaseSchemaEditor",
) -> None:
  PriceGroupModel = cast("PriceGroup", apps.get_model('items', 'PriceGroup'))
  ItemModel = cast("Item", apps.get_model('items', 'Item'))

  quantity_map = {
      "double rolls": 1,
      "KG": 1,
      "L": 1,
      "lb": 1,
      "m": 1,
      "pc": 1,
      "triple rolls": 1,
  }

  with transaction.atomic():
    for item in ItemModel.objects.all():
      if not item.price_group:
        price_group = PriceGroupModel.objects.get_or_create(
            is_organic=item.is_organic,
            is_non_gmo=item.is_non_gmo,
            name=item.name,
            quantity=quantity_map.get(item.packaging.unit.name, 100),
            unit=item.packaging.unit,
        )[0]
        item.price_group = price_group

      item.save()


def backwards_func(
    apps: "Apps",
    schema_editor: "BaseDatabaseSchemaEditor",
) -> None:
  return


class Migration(migrations.Migration):

  dependencies = [
      ('items', '0008_add_item_price_group'),
  ]

  operations = [
      migrations.RunPython(forwards_func, backwards_func),
  ]
