# Generated by Django 4.2.29 on 2026-03-12 19:09

from typing import TYPE_CHECKING, cast

import django.db.models.deletion
from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations, models, transaction
from items import constants

if TYPE_CHECKING:
  from django.apps.registry import Apps
  from django.db.backends.base.schema import BaseDatabaseSchemaEditor
  from items.models import Item, PriceGroup


def forwards_func(
    apps: "Apps",
    schema_editor: "BaseDatabaseSchemaEditor",
) -> None:
  PriceGroupModel = cast("PriceGroup", apps.get_model('items', 'PriceGroup'))
  ItemModel = cast("Item", apps.get_model('items', 'Item'))

  with transaction.atomic():
    for item in ItemModel.objects.all():
      if not item.price_group:
        price_group_name = item.name
        if item.is_organic:
          price_group_name = (
              f"{constants.ITEM_NAME_PREFIX_ORGANIC} {price_group_name}"
          )

        try:
          price_group = PriceGroupModel.objects.get(
              name__iexact=price_group_name
          )
        except ObjectDoesNotExist:
          price_group = PriceGroupModel.objects.create(
              name=price_group_name,
              quantity=100,
              unit=item.packaging.unit,
          )

      item.price_group = price_group
      item.save()


def backwards_func(
    apps: "Apps",
    schema_editor: "BaseDatabaseSchemaEditor",
) -> None:
  return


class Migration(migrations.Migration):

  dependencies = [
      ('items', '0008_add_item_price_group'),
  ]

  operations = [
      migrations.RunPython(forwards_func, backwards_func),
      migrations.AlterField(
          model_name='item',
          name='price_group',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT,
              to='items.pricegroup'
          ),
      ),
  ]
