# Generated by Django 4.2.28 on 2026-02-20 19:28

import django.db.models.deletion
import django.db.models.functions.text
import utilities.models.fields.blonde
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      ('items', '0002_alter_packaging_quantity'),
      ('stores', '0001_initial'),
      ('scrapers', '0002_remove_scraper_pricing_bulk_regex_and_more'),
  ]

  operations = [
      migrations.CreateModel(
          name='Error',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              ('is_reoccurring', models.BooleanField(default=False)),
          ],
      ),
      migrations.CreateModel(
          name='ErrorType',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'name',
                  utilities.models.fields.blonde.BlondeCharField(max_length=80)
              ),
          ],
      ),
      migrations.AddConstraint(
          model_name='errortype',
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower('name'),
              name='Error name must be unique'
          ),
      ),
      migrations.AddField(
          model_name='error',
          name='item',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.CASCADE, to='items.item'
          ),
      ),
      migrations.AddField(
          model_name='error',
          name='scraper_config',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.CASCADE,
              to='scrapers.scraperconfig'
          ),
      ),
      migrations.AddField(
          model_name='error',
          name='store',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.CASCADE, to='stores.store'
          ),
      ),
      migrations.AddField(
          model_name='error',
          name='type',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.CASCADE,
              to='errors.errortype'
          ),
      ),
      migrations.AlterUniqueTogether(
          name='error',
          unique_together={('type', 'item', 'scraper_config', 'store')},
      ),
  ]
