# Generated by Django 4.2.28 on 2026-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ("errors", "0001_initial"),
  ]

  operations = [
      migrations.AddField(
          model_name="error",
          name="count",
          field=models.PositiveIntegerField(default=1),
      ),
  ]
