# Generated by Django 4.2.16 on 2024-09-05 18:02

import django.db.models.deletion
import utilities.models.fields.title
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = []

  operations = [
      migrations.CreateModel(
          name='Report',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              ('name', utilities.models.fields.title.TitleField(max_length=80)),
          ],
          options={
              'abstract': False,
          },
      ),
      migrations.CreateModel(
          name='ReportStore',
          fields=[
              (
                  'id',
                  models.BigAutoField(
                      auto_created=True,
                      primary_key=True,
                      serialize=False,
                      verbose_name='ID'
                  )
              ),
              (
                  'report',
                  models.ForeignKey(
                      on_delete=django.db.models.deletion.PROTECT,
                      to='reports.report'
                  )
              ),
          ],
          options={
              'abstract': False,
          },
      ),
  ]
