# Generated by Django 4.2.16 on 2024-09-05 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

  initial = True

  dependencies = [
      ('reports', '0001_initial'),
      migrations.swappable_dependency(settings.AUTH_USER_MODEL),
      ('items', '0001_initial'),
      ('stores', '0001_initial'),
  ]

  operations = [
      migrations.AddField(
          model_name='reportstore',
          name='store',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT, to='stores.store'
          ),
      ),
      migrations.AddField(
          model_name='report',
          name='item',
          field=models.ManyToManyField(to='items.item'),
      ),
      migrations.AddField(
          model_name='report',
          name='store',
          field=models.ManyToManyField(
              through='reports.ReportStore', to='stores.store'
          ),
      ),
      migrations.AddField(
          model_name='report',
          name='user',
          field=models.ForeignKey(
              on_delete=django.db.models.deletion.PROTECT,
              to=settings.AUTH_USER_MODEL
          ),
      ),
  ]
