# Generated by Django 4.2.20 on 2025-04-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
      ("reports", "0002_initial"),
  ]

  operations = [
      migrations.AddField(
          model_name="report",
          name="is_testing_only",
          field=models.BooleanField(default=False),
      ),
  ]
