# Generated by Django 4.2.28 on 2026-02-26 23:31

from django.db import migrations


class Migration(migrations.Migration):
  dependencies = [
      ("reports", "0003_report_is_testing_only"),
  ]

  operations = [
      migrations.RenameField(
          model_name="report",
          old_name="is_testing_only",
          new_name="is_testing",
      ),
  ]
