# Generated by Django 4.2.28 on 2026-03-02 18:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

  dependencies = [
      ('reports', '0004_report_is_testing'),
  ]

  operations = [
      migrations.AddConstraint(
          model_name='report',
          constraint=models.UniqueConstraint(
              django.db.models.functions.text.Lower('name'),
              name='Report name must be unique'
          ),
      ),
  ]
